apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.surge }}
      maxUnavailable: {{ .Values.strategy.unavailable }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Chart.Name }}-registry
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image" . }}
          resources:
            requests:
              cpu: {{ .Values.container.resources.requests.cpu }}
              memory: {{ .Values.container.resources.requests.memory }}
            limits:
              cpu: {{ .Values.container.resources.limits.cpu }}
              memory: {{ .Values.container.resources.limits.memory }}
          ports:
            - protocol: TCP
              containerPort: {{ .Values.container.port }}
          {{- if .Values.container.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.container.probes.liveness.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.probes.liveness.delay }}
            timeoutSeconds: {{ .Values.container.probes.liveness.timeout }}
            periodSeconds: {{ .Values.container.probes.liveness.period }}
          {{- end }}

          {{- if .Values.container.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.container.probes.readiness.path }}
              port: {{ .Values.container.port }}
            initialDelaySeconds: {{ .Values.container.probes.readiness.delay }}
            timeoutSeconds: {{ .Values.container.probes.readiness.timeout }}
            periodSeconds: {{ .Values.container.probes.readiness.period }}
          {{- end }}
